### ISSUE TITLE
'Say' command does not work

### ISSUE THREAD

**Issue by muradodjag** [BrammyS/Discord-Bot-Template#107]
'Say' command does not work because it is not a subcommand. In HandleSlashCommandAsync(color-chan package), option.Type is a string, and because context.SlashCommandName is null, I get this error: System.ArgumentNullException: Value cannot be null. (Source parameter). But after adding the subcommand, for example if I type **/say subcommand test**, it works. 
Maybe i'm doing something wrong

**Comment by BrammyS** [comment]
Could you include the full error message? And please also include the code where the error occurred in.

P.S. Im currently on holiday, so sorry if i reply late.
