### ISSUE TITLE
Creating your own slash commands!

### ISSUE THREAD

**Issue by BrammyS** [BrammyS/Discord-Bot-Template#44]
### This issue is designed for people that would like to create something during [hacktoberfest](https://hacktoberfest.com).

You will need to get read the [Getting Started guide](https://github.com/BrammyS/Discord-Bot-Template#getting-started) first everything up and running! :D

You can start creating your own commands after this.
Feel free to create a command in the [Commands](https://github.com/BrammyS/Discord-Bot-Template/tree/main/src/Bot.Discord/Commands) folder, that you think would be useful for a Discord bot template, try to avoid really specific commands.

**Comment by federinik** [comment]
Hi @BrammyS,

nice project, I kinda like Discord and gaming stuff, so I thought maybe I could implement an Invite (/invite) command?

**Comment by BrammyS** [comment]
Go ahead! Sounds like a great addition!

**Comment by federinik** [comment]
I'm almost done with the setup, I just need to host an instance of the bot somewhere, do you have any suggestions?

**Comment by BrammyS** [comment]
Anything where you can open a port. There aren't really any hardware requirements. So even a raspberry pi with a cloudflare tunnel will work perfectly. 🤗
