### ISSUE TITLE
Move as much configurations as possible to IConfiguration

### ISSUE THREAD

**Issue by federinik** [BrammyS/Discord-Bot-Template#49]
**Is your feature request related to a problem? Please describe.**
More an enhancement/quality of life than a real feature.

Mongo connection string (`MONGO_CON_STRING`) and Discord Bot's Token (`BOT_TOKEN`) are retrieved using environment variables, this forces developers to change _launchSettings.json_ file to provide their own values during debugging and, therefore, exposingn them to the risk of pushing sensitive data in the repository.

Kinda the same happens for BotId and PublicKey (`Constants.cs` file), but those are not really sensitive data and will mutate very rarely.

**Describe the solution you'd like**
Retrieve `MONGO_CON_STRING` and `BOT_TOKEN` variables from `IConfiguration` object. This would be transparent for those who retrieves data from environment variables, but would enable the use of both appSettings.json file and userSecrets.json file (which are local, encrypted and not versioned in GIT, so perfectly suits storing sensitive datas like connection strings and bot token).

**Comment by BrammyS** [comment]
Btw, I think that the secret manager should be used for tokens and connection strings. https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows

**Comment by federinik** [comment]
It was not very clear, but yes, I was suggesting using Secrets Manager! Anyway, I have a draft on this branch, check it out if you prefer: https://github.com/federinik/Discord-Bot-Template/tree/feature/configs
